### ISSUE TITLE
ERROR: for airflow-init  Container "...." is unhealthy

### ISSUE THREAD

**Issue by tgzw** [maxcotec/Apache-Airflow#2]
Hi. I encounter this error with each docker-compose. I do ``docker-compose up airflow-init`` and I get:

```
Creating network "docker-sequencial-mysql_default" with the default driver
Creating volume "docker-sequencial-mysql_my-db" with default driver
Pulling airflow-init (apache/airflow:2.1.1-python3.8)...
2.1.1-python3.8: Pulling from apache/airflow
72a69066d2fe: Already exists
758aab0c7b73: Already exists
1db83a6395ee: Already exists
b3b8b56b0660: Already exists
513cdf2c811a: Already exists
f0096a955e6e: Pull complete
3dd0143296c5: Pull complete
10e989befd63: Pull complete
d649ea8af400: Pull complete
ead3600791c3: Pull complete
97a57dd5b8ee: Pull complete
52eed500ee52: Pull complete
e6d792052ac4: Pull complete
Digest: sha256:47eaa61e2f45d7e644ab6643d8a1c12ae61c504d7e0c6ffc83ff7caa29f3c787
Status: Downloaded newer image for apache/airflow:2.1.1-python3.8
Creating docker-sequencial-mysql_mysql_1 ... done

ERROR: for airflow-init  Container "1cff719a31db" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

What could I do to build the docker container succesfully?

**Comment by mineoreitz** [comment]
Im having a similar problem..

After runing airflow-init... when i try do run airflow-scheduler its stuck on monitoring_dag_mysql_1 is up-to-date

**Comment by maxcotec** [comment]
Please change mysql service healthcheck test from this 
`test: "/etc/init.d/mysql status"`
to this 
`test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", '-pairflow']`
Optionally you may also reduce the reties from 120 to 2or3 to reduce wiat time. normally the mysql service shouldn't take long to become healthy. 

Also if anyone trying on Mac M1, add `platform: linux/x86_64` in mysql service and &airflow-common.
